const DELIMETER_FOR_REQUEST_ARG = ',';
const PATH_TYPE_SOLUTION = 'S';
const QUEUE_STRATEGY_PRIORITY_QUEUE = 'P';
const ANIMATION_DURATION = 10;
const ANIMATION_DURATION_FOR_SWAP = 100;
export { DELIMETER_FOR_REQUEST_ARG, PATH_TYPE_SOLUTION, QUEUE_STRATEGY_PRIORITY_QUEUE, ANIMATION_DURATION, ANIMATION_DURATION_FOR_SWAP };